plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

ext {
    nettyVersion = '4.1.115.Final'
}

dependencies {
    implementation "io.netty:netty-all:${nettyVersion}"
    implementation 'org.yaml:snakeyaml:2.2'

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'com.aicoin.proxy.ProxyMain'
}

test {
    useJUnitPlatform()
}

run {
    standardInput = System.in
}
